version: '3.8'

volumes:
  db:
    driver: local

services:
  postgres:
    # The version should be synchronized with the postgresql-client installed in the docker test images
    image: postgres:15.2
    restart: always
    container_name: coffee_roulette_postgres
    ports:
      - '127.0.0.1:5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data