name: Run tests action
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
      - run: bundle install && npm ci
      - name: Start containers
        run: docker compose up -d
      - run: echo "The containers have been started!"
      - name: Run migrations
        run: rails db:create && rails db:migrate
      - name: Run tests
        env:
          CI: true
        run: bundle exec rake

  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - name: Format with Biome and then run ESLint
        run: npm run format:lint

